### ISSUE TITLE
Error while running caesar_solver.py

### ISSUE THREAD

**Issue by mzfr** [jamchamb/etao#2]
I am getting error when I try to run caesar_solver.py
```Traceback
Traceback (most recent call last):
  File "caesar_solver.py", line 31, in <module>
    main()
  File "caesar_solver.py", line 13, in main
    scorer = NgramFrequencyScorer(freq=ENGLISH_DIGRAMS)
  File "/usr/local/lib/python3.5/dist-packages/etao/scorers.py", line 20, in __init__
    ngram_length = len(freq.keys()[0])
TypeError: 'dict_keys' object does not support indexing
```

I have installed `etao` as a pip package

**Comment by jamchamb** [comment]
Try running it with Python 2, I have not tested in Python 3
